### ISSUE TITLE
Physics is frame dependent

### ISSUE THREAD

**Issue by Pistonnoob** [Chringo/SSP#65] opened 2016-12-15 13:56 UTC
The physics is frame dependent.

**Comment by TobbetheStalker** [comment] 2016-12-20 08:10
The fix exist in the Demo branch but since the camera is incomplete, I dont want to merge it with dev. We will probably have to redo the fix sepratly.

**Comment by Chringo** [comment] 2017-01-04 16:53
Is this solved with following commit?
https://github.com/Chringo/SSP/pull/74/commits/b52387f29a73a36184fcb4799ff83b9c79afca4a

This commit has been merged with dev from pull request #74.

**Comment by Chringo** [comment] 2017-01-05 08:16
Confirmed.

**Closed as completed by Chringo** 2017-01-05 08:16 UTC
Labels: bug
